### ISSUE TITLE
Can't Upload Hello World

### ISSUE THREAD

**Issue by Andy1213** [empug/road-quality-project#3]
Uploads are disabled. Please grant access. Thanks!

**Comment by patchedsoul** [comment]
looking now.

**Comment by caretnavigator** [comment]
Do we need a facilitator code to get started?

**Comment by caretnavigator** [comment]
Sorry I spoke too soon. I just got the Hello World! program to work.

**Comment by rahuljc1992** [comment]
Great!! I think its a good start to our project.


Thanks,
Rahul JC.

**Comment by patchedsoul** [comment]
Closing as pull requests were reviewed. additional info found: [https://help.github.com/articles/creating-a-pull-request/](https://help.github.com/articles/creating-a-pull-request/)
