### ISSUE TITLE
Is MicroPython + BLE + MicroBit Possible?

### ISSUE THREAD

**Issue by Andy1213** [empug/road-quality-project#9]
I ran across this while learning more about the MicroBit BLE:

http://microbit-micropython.readthedocs.io/en/latest/ble.html

The EVOthings accelerometer demo uses JavaScript. Will we have a problem if we use the BLE to communicate between the MicroBit and a cell phone? I thought that was the direction we were going in.

**Comment by patchedsoul** [comment]
Yeah, I'm discovering the same thing. It's clear we have to refactor something here unfortunately. The BLE stack consumes somewhere between 12-17K alone. MicroPython dev's have closed the enhancement citing the micro:bit's space constraints as a show stopper for now. 
Stand by as I'm researching some solutions right now....

**Comment by violentlyhappi** [comment]
see July 15 meeting notes (raspberry pi + micro:bit is accepted solution)
